version: "3.7"
networks:
  internal:
    driver: "bridge"

volumes:
  database:
    driver: "local"

services:
  api:
    build:
      context: .
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    networks:
      - internal
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always

  database:
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_NAME:-sample}
      MYSQL_USER: ${DB_USERNAME:-admin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    restart: always
